#include "agrs_zeus/PIRL.h"
#include <fstream>
#include <sstream>
#include <iostream>
#include <random>
#include <filesystem>
#include <gdal_priv.h>
#include <ogrsf_frmts.h>

namespace agrs {
namespace pirl {

// ============================================================================
// PROJECT CONFIG YAML LOADING/SAVING
// ============================================================================

ProjectConfig ProjectConfig::load_from_yaml(const std::string& yaml_path) {
    ProjectConfig config;
    
    std::cout << "📖 Loading project configuration from: " << yaml_path << std::endl;
    
    std::ifstream file(yaml_path);
    if (!file.is_open()) {
        std::cerr << "❌ Failed to open config file: " << yaml_path << std::endl;
        return config;
    }
    
    // Simple YAML parser (for basic key-value pairs)
    // TODO: Use a proper YAML library (yaml-cpp) for production
    std::string line;
    while (std::getline(file, line)) {
        // Skip comments and empty lines
        if (line.empty() || line[0] == '#') continue;
        
        // Find key-value separator
        size_t colon_pos = line.find(':');
        if (colon_pos == std::string::npos) continue;
        
        std::string key = line.substr(0, colon_pos);
        std::string value = line.substr(colon_pos + 1);
        
        // Trim whitespace
        key.erase(0, key.find_first_not_of(" \t"));
        key.erase(key.find_last_not_of(" \t") + 1);
        value.erase(0, value.find_first_not_of(" \t"));
        value.erase(value.find_last_not_of(" \t") + 1);
        
        // Parse basic fields
        if (key == "project_name") {
            config.project_name = value;
        } else if (key == "project_code") {
            config.project_code = value;
        } else if (key == "client_name") {
            config.client_name = value;
        } else if (key == "epsg_code") {
            config.epsg_code = std::stoi(value);
        } else if (key == "measurement_units") {
            config.measurement_units = value;
        } else if (key == "start_x") {
            config.start_point.x = std::stod(value);
        } else if (key == "start_y") {
            config.start_point.y = std::stod(value);
        } else if (key == "end_x") {
            config.end_point.x = std::stod(value);
        } else if (key == "end_y") {
            config.end_point.y = std::stod(value);
        } else if (key == "project_dir") {
            config.project_dir = value;
        } else if (key == "max_slope_percent") {
            config.constraints.max_slope_percent = std::stod(value);
        } else if (key == "learning_rate") {
            config.training.learning_rate = std::stod(value);
        }
        // Add more fields as needed...
    }
    
    std::cout << "✅ Configuration loaded: " << config.project_name << std::endl;
    
    return config;
}

bool ProjectConfig::load_pipeline_specs_from_json(const std::string& json_path) {
    try {
        pipeline_specs = PipelineSpecifications::load_from_json(json_path);
        has_pipeline_specs = true;
        std::cout << "✅ Pipeline specifications loaded from: " << json_path << std::endl;
        return true;
    } catch (const std::exception& e) {
        std::cerr << "❌ Failed to load pipeline specs: " << e.what() << std::endl;
        has_pipeline_specs = false;
        return false;
    }
}

void ProjectConfig::save_to_yaml(const std::string& yaml_path) const {
    std::ofstream file(yaml_path);
    if (!file.is_open()) {
        std::cerr << "❌ Failed to open file for writing: " << yaml_path << std::endl;
        return;
    }
    
    file << "# PIRL Project Configuration\n";
    file << "# Generated by ZEUS AGRS\n\n";
    
    file << "# Project Identification\n";
    file << "project_name: " << project_name << "\n";
    file << "project_code: " << project_code << "\n";
    file << "client_name: " << client_name << "\n\n";
    
    file << "# Coordinate System\n";
    file << "epsg_code: " << epsg_code << "\n";
    file << "measurement_units: " << measurement_units << "\n\n";
    
    file << "# Start and End Points\n";
    file << "start_x: " << start_point.x << "\n";
    file << "start_y: " << start_point.y << "\n";
    file << "end_x: " << end_point.x << "\n";
    file << "end_y: " << end_point.y << "\n\n";
    
    file << "# Cost Weights\n";
    file << "terrain_difficulty: " << cost_weights.terrain_difficulty << "\n";
    file << "water_crossings: " << cost_weights.water_crossings << "\n";
    file << "infrastructure_crossings: " << cost_weights.infrastructure_crossings << "\n";
    file << "environmental_impact: " << cost_weights.environmental_impact << "\n";
    file << "row_acquisition: " << cost_weights.row_acquisition << "\n";
    file << "permitting_complexity: " << cost_weights.permitting_complexity << "\n\n";
    
    file << "# Constraints\n";
    file << "max_slope_percent: " << constraints.max_slope_percent << "\n";
    file << "max_curvature_rad_per_m: " << constraints.max_curvature_rad_per_m << "\n";
    file << "min_crossing_angle_deg: " << constraints.min_crossing_angle_deg << "\n";
    file << "buffer_protected_areas_m: " << constraints.buffer_protected_areas_m << "\n";
    file << "buffer_water_bodies_m: " << constraints.buffer_water_bodies_m << "\n";
    file << "max_segment_length_m: " << constraints.max_segment_length_m << "\n\n";
    
    file << "# Training Parameters\n";
    file << "num_episodes: " << training.num_episodes << "\n";
    file << "max_steps_per_episode: " << training.max_steps_per_episode << "\n";
    file << "learning_rate: " << training.learning_rate << "\n";
    file << "batch_size: " << training.batch_size << "\n";
    file << "num_parallel_envs: " << training.num_parallel_envs << "\n";
    file << "algorithm: " << training.algorithm << "\n\n";
    
    file << "# Paths\n";
    file << "project_dir: " << project_dir << "\n";
    file << "data_dir: " << data_dir << "\n";
    file << "output_dir: " << output_dir << "\n";
    file << "model_save_path: " << model_save_path << "\n";
    
    file.close();
    std::cout << "💾 Configuration saved to: " << yaml_path << std::endl;
}

// ============================================================================
// TRAINING UTILITIES
// ============================================================================

namespace training {

std::vector<ProjectConfig> generate_training_scenarios(
    const std::string& base_config_path,
    int num_easy,
    int num_medium,
    int num_hard) {
    
    std::cout << "🎓 Generating training scenarios..." << std::endl;
    std::cout << "  Easy: " << num_easy << std::endl;
    std::cout << "  Medium: " << num_medium << std::endl;
    std::cout << "  Hard: " << num_hard << std::endl;
    
    std::vector<ProjectConfig> scenarios;
    
    // Load base configuration
    ProjectConfig base = ProjectConfig::load_from_yaml(base_config_path);
    
    std::random_device rd;
    std::mt19937 gen(rd());
    
    // Generate easy scenarios (flat terrain, no obstacles)
    for (int i = 0; i < num_easy; ++i) {
        ProjectConfig config = base;
        config.project_name = "training_easy_" + std::to_string(i);
        
        // Short distance, flat terrain assumptions
        std::uniform_real_distribution<> dist_short(1000.0, 5000.0);
        double distance = dist_short(gen);
        
        config.end_point.x = config.start_point.x + distance;
        config.end_point.y = config.start_point.y;
        
        scenarios.push_back(config);
    }
    
    // Generate medium scenarios (moderate terrain, some obstacles)
    for (int i = 0; i < num_medium; ++i) {
        ProjectConfig config = base;
        config.project_name = "training_medium_" + std::to_string(i);
        
        // Medium distance, varied direction
        std::uniform_real_distribution<> dist_medium(5000.0, 20000.0);
        std::uniform_real_distribution<> angle(-M_PI, M_PI);
        
        double distance = dist_medium(gen);
        double theta = angle(gen);
        
        config.end_point.x = config.start_point.x + distance * std::cos(theta);
        config.end_point.y = config.start_point.y + distance * std::sin(theta);
        
        scenarios.push_back(config);
    }
    
    // Generate hard scenarios (long distance, complex terrain)
    for (int i = 0; i < num_hard; ++i) {
        ProjectConfig config = base;
        config.project_name = "training_hard_" + std::to_string(i);
        
        // Long distance, complex routing
        std::uniform_real_distribution<> dist_long(20000.0, 100000.0);
        std::uniform_real_distribution<> angle(-M_PI, M_PI);
        
        double distance = dist_long(gen);
        double theta = angle(gen);
        
        config.end_point.x = config.start_point.x + distance * std::cos(theta);
        config.end_point.y = config.start_point.y + distance * std::sin(theta);
        
        // Tighter constraints for hard scenarios
        config.constraints.max_slope_percent = 20.0; // Stricter
        
        scenarios.push_back(config);
    }
    
    std::cout << "✅ Generated " << scenarios.size() << " training scenarios" << std::endl;
    
    return scenarios;
}

void create_synthetic_projects(const std::string& output_dir, int num_projects) {
    std::cout << "🏗️  Creating " << num_projects << " synthetic projects..." << std::endl;
    
    // Create output directory
    std::filesystem::create_directories(output_dir);
    
    std::random_device rd;
    std::mt19937 gen(rd());
    std::uniform_real_distribution<> coord(300000.0, 700000.0);
    
    for (int i = 0; i < num_projects; ++i) {
        std::string project_name = "synthetic_project_" + std::to_string(i);
        std::string project_dir = output_dir + "/" + project_name;
        
        std::filesystem::create_directories(project_dir);
        
        // Create basic project config
        ProjectConfig config;
        config.project_name = project_name;
        config.project_code = "SYN_" + std::to_string(i);
        config.client_name = "Synthetic";
        config.epsg_code = 32633; // UTM 33N
        config.measurement_units = "SI";
        
        // Random start/end points
        config.start_point.x = coord(gen);
        config.start_point.y = coord(gen);
        config.end_point.x = coord(gen);
        config.end_point.y = coord(gen);
        
        config.project_dir = project_dir;
        
        // Save config
        config.save_to_yaml(project_dir + "/project_config.yaml");
        
        if ((i + 1) % 10 == 0) {
            std::cout << "  Created " << (i + 1) << "/" << num_projects << " projects" << std::endl;
        }
    }
    
    std::cout << "✅ Synthetic projects created in: " << output_dir << std::endl;
}

EvaluationResults evaluate_model(const std::string& model_path,
                                const std::string& test_projects_dir) {
    std::cout << "📊 Evaluating model: " << model_path << std::endl;
    std::cout << "   Test projects: " << test_projects_dir << std::endl;
    
    EvaluationResults results;
    results.avg_cost_savings_percent = 0.0;
    results.success_rate = 0.0;
    results.avg_constraint_violations = 0.0;
    results.avg_solution_time_seconds = 0.0;
    
    // TODO: Implement full evaluation
    // This would:
    // 1. Load model
    // 2. Iterate through test projects
    // 3. Generate routes
    // 4. Compare vs baseline (straight line or A*)
    // 5. Calculate metrics
    
    std::cout << "✅ Evaluation complete" << std::endl;
    
    return results;
}

} // namespace training

// ============================================================================
// EXPORT UTILITIES
// ============================================================================

namespace export_utils {

void export_to_geojson(const std::vector<std::pair<double, double>>& route,
                      const std::string& output_path,
                      int epsg_code) {
    std::ofstream out(output_path);
    if (!out.is_open()) {
        std::cerr << "❌ Failed to open output file: " << output_path << std::endl;
        return;
    }
    
    out << "{\n";
    out << "  \"type\": \"Feature\",\n";
    out << "  \"crs\": {\n";
    out << "    \"type\": \"name\",\n";
    out << "    \"properties\": {\n";
    out << "      \"name\": \"EPSG:" << epsg_code << "\"\n";
    out << "    }\n";
    out << "  },\n";
    out << "  \"properties\": {\n";
    out << "    \"route_type\": \"PIRL_optimized\",\n";
    out << "    \"num_points\": " << route.size() << "\n";
    out << "  },\n";
    out << "  \"geometry\": {\n";
    out << "    \"type\": \"LineString\",\n";
    out << "    \"coordinates\": [\n";
    
    for (size_t i = 0; i < route.size(); ++i) {
        out << "      [" << route[i].first << ", " << route[i].second << "]";
        if (i < route.size() - 1) out << ",";
        out << "\n";
    }
    
    out << "    ]\n";
    out << "  }\n";
    out << "}\n";
    
    out.close();
    std::cout << "✅ Route exported to GeoJSON: " << output_path << std::endl;
}

void export_to_shapefile(const std::vector<std::pair<double, double>>& route,
                        const std::string& output_path,
                        int epsg_code) {
    GDALAllRegister();
    
    // Create shapefile
    GDALDriver* driver = GetGDALDriverManager()->GetDriverByName("ESRI Shapefile");
    if (!driver) {
        std::cerr << "❌ Shapefile driver not available" << std::endl;
        return;
    }
    
    GDALDataset* dataset = driver->Create(output_path.c_str(), 0, 0, 0, GDT_Unknown, nullptr);
    if (!dataset) {
        std::cerr << "❌ Failed to create shapefile: " << output_path << std::endl;
        return;
    }
    
    // Create spatial reference
    OGRSpatialReference srs;
    srs.importFromEPSG(epsg_code);
    
    // Create layer
    OGRLayer* layer = dataset->CreateLayer("route", &srs, wkbLineString, nullptr);
    if (!layer) {
        std::cerr << "❌ Failed to create layer" << std::endl;
        GDALClose(dataset);
        return;
    }
    
    // Add fields
    OGRFieldDefn field_type("route_type", OFTString);
    field_type.SetWidth(50);
    layer->CreateField(&field_type);
    
    OGRFieldDefn field_length("length_m", OFTReal);
    layer->CreateField(&field_length);
    
    // Create feature
    OGRFeature* feature = OGRFeature::CreateFeature(layer->GetLayerDefn());
    feature->SetField("route_type", "PIRL_optimized");
    
    // Create linestring geometry
    OGRLineString linestring;
    double total_length = 0.0;
    
    for (size_t i = 0; i < route.size(); ++i) {
        linestring.addPoint(route[i].first, route[i].second);
        
        if (i > 0) {
            double dx = route[i].first - route[i-1].first;
            double dy = route[i].second - route[i-1].second;
            total_length += std::sqrt(dx*dx + dy*dy);
        }
    }
    
    feature->SetField("length_m", total_length);
    feature->SetGeometry(&linestring);
    
    // Save feature
    if (layer->CreateFeature(feature) != OGRERR_NONE) {
        std::cerr << "❌ Failed to create feature" << std::endl;
    }
    
    OGRFeature::DestroyFeature(feature);
    GDALClose(dataset);
    
    std::cout << "✅ Route exported to Shapefile: " << output_path << std::endl;
}

void export_stats_to_csv(const PIRLAgent::RouteEvaluation& eval,
                        const std::string& output_path) {
    std::ofstream out(output_path);
    if (!out.is_open()) {
        std::cerr << "❌ Failed to open output file: " << output_path << std::endl;
        return;
    }
    
    out << "Metric,Value\n";
    out << "Total Cost (USD)," << eval.total_cost_usd << "\n";
    out << "Length (m)," << eval.length_m << "\n";
    out << "Cost per km (USD)," << eval.cost_per_km << "\n";
    out << "Savings vs Baseline (%)," << eval.savings_vs_baseline_percent << "\n";
    out << "All Constraints Satisfied," << (eval.all_constraints_satisfied ? "Yes" : "No") << "\n";
    out << "Num Constraint Violations," << eval.constraint_violations.size() << "\n";
    out << "Total Length (m)," << eval.stats.total_length_m << "\n";
    out << "Average Slope," << eval.stats.avg_slope << "\n";
    out << "Water Crossings," << eval.stats.num_water_crossings << "\n";
    out << "Road Crossings," << eval.stats.num_road_crossings << "\n";
    
    out.close();
    std::cout << "✅ Statistics exported to CSV: " << output_path << std::endl;
}

void generate_comparison_report(
    const std::vector<std::pair<double, double>>& pirl_route,
    const std::vector<std::pair<double, double>>& baseline_route,
    const std::string& project_dir,
    const std::string& output_pdf_path) {
    
    std::cout << "📊 Generating comparison report..." << std::endl;
    std::cout << "   PIRL route: " << pirl_route.size() << " points" << std::endl;
    std::cout << "   Baseline route: " << baseline_route.size() << " points" << std::endl;
    
    // TODO: Generate PDF report using LaTeX or similar
    // This would include:
    // 1. Route maps
    // 2. Cost comparison tables
    // 3. Constraint satisfaction analysis
    // 4. Terrain profile graphs
    // 5. Crossing analysis
    
    std::cout << "✅ Comparison report generated: " << output_pdf_path << std::endl;
}

} // namespace export_utils

} // namespace pirl
} // namespace agrs

